spring:
    config:
        activate:
            on-profile: prod
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: ${SMTP_HOST}
        port: ${SMTP_PORT}
        username: ${SMTP_USERNAME}
        password: ${SMTP_PASSWORD}
        protocol: smtp
        properties:
            mail:
                smtp:
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000
                    auth: true
                    starttls:
                        enable: true
                        required: true
samichlaus:
    backend-server: ${BACKEND_SERVER}
    frontend-server: ${FRONTEND_SERVER}
    path-to-osm-file: ${PATH_TO_OSM_FILE}
    path-to-graphhopper-data: ${PATH_TO_GRAPHHOPPER_DATA}
    path-to-excel-template: ${PATH_TO_EXCEL_TEMPLATE}
    path-to-samichlaus-icon: ${PATH_TO_SAMICHLAUS_ICON}
    path-to-samichlaus-email: ${PATH_TO_SAMICHLAUS_EMAIL}
---
spring:
    config:
        activate:
            on-profile: develop
    datasource:
        url: jdbc:h2:mem:testdb # Using H2 in-memory database
        driver-class-name: org.h2.Driver
        username: test
        password: test
        jpa:
            hibernate:
                ddl-auto: update # Re-create database schema on each test run
            show-sql: true
            database: h2
            database-platform: org.hibernate.dialect.H2Dialect
    mail:
        host: smtp
        port: 587
        username: ${SMTP_USERNAME}
        password: ${SMTP_PASSWORD}
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                debug: true
samichlaus:
    backend-server: http://localhost:8080
    frontend-server: http://localhost:5173
    path-to-osm-file: ${PATH_TO_OSM_FILE}
    path-to-graphhopper-data: ${PATH_TO_GRAPHHOPPER_DATA}
    path-to-excel-template: ${PATH_TO_EXCEL_TEMPLATE}
    path-to-samichlaus-icon: ${PATH_TO_SAMICHLAUS_ICON}
    path-to-samichlaus-email: ${PATH_TO_SAMICHLAUS_EMAIL}
logging:
    level:
        root: INFO
        org:
            springframework: DEBUG
---
spring:
    config:
        activate:
            on-profile: testpostgres
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/samichlaus
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: smtp-mail.outlook.com
        port: 587
        username: ${SMTP_USERNAME}
        password: ${SMTP_PASSWORD}
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                debug: true
samichlaus:
    backend-server: http://localhost:8080
    frontend-server: http://localhost:5173
    path-to-osm-file: ${PATH_TO_OSM_FILE}
    path-to-graphhopper-data: ${PATH_TO_GRAPHHOPPER_DATA}
    path-to-excel-template: ${PATH_TO_EXCEL_TEMPLATE}
    path-to-samichlaus-icon: ${PATH_TO_SAMICHLAUS_ICON}
    path-to-samichlaus-email: ${PATH_TO_SAMICHLAUS_EMAIL}
logging:
    level:
        root: INFO
        org:
            springframework: DEBUG